export {Header} from './Header/Header'
export {Footer} from './Footer/Footer'
export {Menu} from './Menu/Menu'
export {Promo} from './Promo/Promo'
export {About} from './About/About'
export {Services} from './Services/Services'
export {ContactUs} from './ContactUs/ContactUs'
export {Terms} from './Terms/Terms'
